app:
  env: "development"
  port: 8083
  context_path: "/promotion-price-mapping-processor-schedule"
  host: "localhost"
  root_path: "/api"
  version: 1.0
database:
  host: ec2-34-199-68-114.compute-1.amazonaws.com
  name: d833p6a5jerefa
  user: ldpjsnnuzgquvw
  pass: de486f13dcf0d3f26b3809dd5ae2699a1c0c09037fbd2797c2795af484068284
  port: 5432
  ssl: disable
  timezone: Asia/Bangkok
endpoint:
  strapi-information-gateway:
    host: "http://localhost:8080"
    path: "/strapi-information-gateway/api/v1/strapi"
  promotion:
    path: /api/promotions
    query: ?populate[Group][populate]=*&populate[Discount][populate]=*
GIN_MODE: "debug"
cron:
  every: 1
  at: 13:30
